# Generated by Django 4.2.1 on 2023-05-31 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaciCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_modify', models.DateTimeField(auto_now_add=True)),
                ('aim', models.CharField(max_length=255, verbose_name='Что мы пытаемся достичь?')),
                ('if_not_reached', models.CharField(max_length=255, verbose_name='Что произойдёт, если цель не будет достигнута?')),
                ('aim_type', models.IntegerField(choices=[(1, 'Принять решение'), (2, 'Придумать идею'), (3, 'Синхронизироваться между собой'), (4, 'Прочее')], default=1, verbose_name='Вид встречи')),
                ('dt_meeting', models.DateTimeField(null=True, verbose_name='Дата и время')),
                ('duration', models.IntegerField(default=30, verbose_name='Длительность')),
                ('place', models.CharField(blank=True, default='', max_length=100, verbose_name='Место')),
                ('key_thoughts', models.TextField(blank=True, default='', max_length=10000, verbose_name='Ключевые мысли')),
                ('parked_thoughts', models.TextField(blank=True, default='', max_length=10000, verbose_name='Парковка')),
                ('other_agreements', models.TextField(blank=True, default='', max_length=10000, verbose_name='Прочие договорённости')),
                ('step', models.IntegerField(default=1, verbose_name='Шаг')),
                ('is_closed', models.IntegerField(default=0, verbose_name='Холст закрыт')),
                ('meeting_status', models.IntegerField(choices=[(1, 'Редактируется'), (2, 'Началась'), (3, 'Окончена')], default=1, verbose_name='Статус встречи')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Холст фасилитации',
                'verbose_name_plural': 'Холсты фасилитации',
                'db_table': 'app_faci_canvas',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_what', models.CharField(max_length=200, verbose_name='В каком вопросе компетентен')),
                ('themes', models.CharField(blank=True, default='', max_length=1000, verbose_name='Предлагаемые темы')),
                ('themes_duration', models.IntegerField(default=5, verbose_name='Длительность выступления, минуты')),
                ('questions', models.CharField(blank=True, default='', max_length=2000, verbose_name='Мнения и вопросы')),
                ('faci_canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faci.facicanvas')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faci_members', to=settings.AUTH_USER_MODEL)),
                ('inviting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faci_member_inviters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник встречи',
                'verbose_name_plural': 'Участники встречи',
                'db_table': 'app_faci_member',
            },
        ),
    ]
