# Generated by Django 4.2.1 on 2023-06-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Обязательный участник встречи', 'verbose_name_plural': 'Обязательные участники встречи'},
        ),
        migrations.AddField(
            model_name='facicanvas',
            name='solutions',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Первоначальные решения'),
        ),
        migrations.AddField(
            model_name='member',
            name='counter_offer',
            field=models.CharField(blank=True, default='', help_text='предложение, которое заменит собой предложение инициатора встречи', max_length=2000, verbose_name='Встречные предложения'),
        ),
        migrations.AddField(
            model_name='member',
            name='fundamental_objections',
            field=models.CharField(blank=True, default='', help_text='веские причины, отменяющие решения/предложения инициатора встречи, делающие поставленный вопрос ничтожным', max_length=2000, verbose_name='Принципиальные возражения'),
        ),
        migrations.AddField(
            model_name='member',
            name='suggested_solutions',
            field=models.CharField(blank=True, default='', help_text='дополнительные предложения для решения проблемы, обозначенной инициатором встречи', max_length=2000, verbose_name='Предлагаемые решения'),
        ),
        migrations.AlterField(
            model_name='member',
            name='questions',
            field=models.CharField(blank=True, default='', help_text='вопросы, возникшие касательно темы встречи', max_length=2000, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='member',
            name='themes',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Тема выступления участника'),
        ),
    ]
