# Generated by Django 4.2.1 on 2023-10-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0002_alter_member_options_facicanvas_solutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='faci_canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='faci.facicanvas'),
        ),
    ]
