# Generated by Django 4.2.1 on 2024-03-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0004_parkedthoughts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facicanvas',
            name='parked_thoughts',
        ),
    ]
