# Generated by Django 4.2.1 on 2024-03-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0005_remove_facicanvas_parked_thoughts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkedthoughts',
            name='faci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_thoughts', to='faci.facicanvas'),
        ),
    ]
