# Generated by Django 4.2.1 on 2024-03-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faci', '0006_alter_parkedthoughts_faci'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkedthoughts',
            options={'verbose_name': 'Припаркованная мысли', 'verbose_name_plural': 'Припаркованные мысли'},
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_modify', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(max_length=1000, verbose_name='Тема выступления')),
                ('duration', models.IntegerField(verbose_name='Длительность выступления, минуты')),
                ('faci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='faci.facicanvas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тема встречи',
                'verbose_name_plural': 'Темы встречи',
            },
        ),
    ]
