# Generated by Django 4.2.1 on 2024-03-24 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faci', '0009_remove_facicanvas_key_thoughts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_modify', models.DateTimeField(auto_now_add=True)),
                ('expression', models.CharField(max_length=1000, verbose_name='Ключевая мысль')),
                ('expression_type', models.IntegerField(choices=[(1, 'Вопросы'), (2, 'Принципиальные возражения'), (3, 'Предлагаемые решения'), (4, 'Встречные предложения')], verbose_name='Тип высказывания')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='faci.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Высказывание к теме',
                'verbose_name_plural': 'Высказывания к теме',
            },
        ),
    ]
