# Generated by Django 4.2.1 on 2024-03-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0012_alter_theme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='facicanvas',
            name='form_of_feedback',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на внешнюю форму обратной связи'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Подробное описание'),
        ),
    ]
