# Generated by Django 4.2.1 on 2024-03-26 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faci', '0013_facicanvas_form_of_feedback_alter_theme_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_modify', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.CharField(max_length=1000, verbose_name='Текст соглашения')),
                ('expire_dt', models.DateTimeField(null=True, verbose_name='Срок выполнения')),
                ('done_dt', models.DateTimeField(null=True, verbose_name='Дата, когда задача была выполнена')),
                ('faci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='faci.facicanvas')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_resp', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Итоговое соглашение',
                'verbose_name_plural': 'Итоговые соглашения',
            },
        ),
    ]
