# Generated by Django 4.2.1 on 2024-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0014_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facicanvas',
            name='other_agreements',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement',
            field=models.CharField(max_length=2000, verbose_name='Текст соглашения'),
        ),
    ]
