# Generated by Django 4.2.1 on 2024-03-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0016_facicanvas_when_finished_facicanvas_when_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='facicanvas',
            name='duration_actual',
            field=models.IntegerField(null=True, verbose_name='Длительность по факту'),
        ),
        migrations.AlterField(
            model_name='facicanvas',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Длительность по плану'),
        ),
    ]
